### ISSUE TITLE
missing materials

### ISSUE THREAD

**Issue by carloshE17** [yfain/Java4Kids#10]
Hello Mr. Fain, thank you for your wonderful book. It make it easier to understand the Java fundamentals.
I noticed, at the end of each chapter, some missing information related to the chapter topic; for example, in chapter 2.3.1, in the section "tip" it mentions a link document to learn more about IDEA's hot keys, and there is not link at all (Same with the remaining chapters).
Are there some addition readings and/or materials available to support and improve the learning experience, that I can access to?
And if it does, how can I get them?
Thank you for your time and efforts to help us out.
Maria and Carlos

**Comment by yfain** [comment]
Thanks. Will fix the text. Meanwhile, here's the link that was missing: https://resources.jetbrains.com/assets/products/intellij-idea/IntelliJIDEA_ReferenceCard.pdf

**Comment by carloshE17** [comment]
Thanks. Are there additional materials for the subsequent chapters?
Maria & Carlos
