### ISSUE TITLE
Exact Creative Commons license

### ISSUE THREAD

**Issue by gdagrow** [yfain/Java4Kids#13]
I tried searching on your website but I can not find the exact CC license you want to use for this book.

This is important because CC licenses approved for Free Cultural Works https://creativecommons.org/share-your-work/public-domain/freeworks/  are very different to the CC licenses which are not Approved for Free Cultural Works.

Can you add a LICENSE file to clarify all this, or link to the exact CC license you want to use?

**Comment by yfain** [comment]
Added

**Comment by gdagrow** [comment]
@yfain Sorry that I was unclear, but 
 https://creativecommons.org/share-your-work/public-domain/freeworks/ is not a license, it just explains what Free Cultural Works are.

There are several Creative Commons (CC) licenses and so you need to just choose one if you want your work to be a CC-work.

There is a spectrum of licenses from most open to least open starting from [CC0](https://creativecommons.org/choose/zero/) Dedicate to the Public Domain (all rights waived), which is the most open, but you retain no rights.

To add a license, adding a file or statement to your book like this would actually license the work:

"This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/)."

But you should choose the actual license you want using a tool like https://creativecommons.org/choose/ or CC0, if you want public domain.
